### ISSUE TITLE
Hi, the size seems to not work

### ISSUE THREAD

**Issue by yourchoice** [Jacob87/raty-fa#6]
Hi, the size option seems to not work

**Comment by iOvergaard** [comment]
If you want to change the size of the stars, this should be done using CSS:

``` css
#score { font-size: 20px; }
```

The advantage of having stars as a font is, that the size will follow your general CSS rules. The `size` option is meant solely for implying the actual size of the stars, which in turn is used for various calculations. This option is usually not necessary to provide, because the module will try and calculate the actual size during runtime.

**Comment by yourchoice** [comment]
yes, in this way working.

Thank's, nice work
